package com.quentin.example.domain;

import java.util.Date;

public class BasicSiteVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.site_id
     *
     * @mbggenerated
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.site_code
     *
     * @mbggenerated
     */
    private String siteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.site_name
     *
     * @mbggenerated
     */
    private String siteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.site_pinyin
     *
     * @mbggenerated
     */
    private String sitePinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.site_type
     *
     * @mbggenerated
     */
    private String siteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.parent_site_code
     *
     * @mbggenerated
     */
    private String parentSiteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.rd_status
     *
     * @mbggenerated
     */
    private Integer rdStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.last_time
     *
     * @mbggenerated
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.updator
     *
     * @mbggenerated
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_site
     *
     * @mbggenerated
     */
    public BasicSiteVO(Integer siteId, String siteCode, String siteName, String sitePinyin, String siteType, String parentSiteCode, Integer rdStatus, Date lastTime, String creator, Date createTime, String updator, Date updateTime, Integer isDeleted) {
        this.siteId = siteId;
        this.siteCode = siteCode;
        this.siteName = siteName;
        this.sitePinyin = sitePinyin;
        this.siteType = siteType;
        this.parentSiteCode = parentSiteCode;
        this.rdStatus = rdStatus;
        this.lastTime = lastTime;
        this.creator = creator;
        this.createTime = createTime;
        this.updator = updator;
        this.updateTime = updateTime;
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_site.site_id
     *
     * @return the value of t_basic_site.site_id
     *
     * @mbggenerated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_site.site_code
     *
     * @return the value of t_basic_site.site_code
     *
     * @mbggenerated
     */
    public String getSiteCode() {
        return siteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_site.site_name
     *
     * @return the value of t_basic_site.site_name
     *
     * @mbggenerated
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_site.site_pinyin
     *
     * @return the value of t_basic_site.site_pinyin
     *
     * @mbggenerated
     */
    public String getSitePinyin() {
        return sitePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_site.site_type
     *
     * @return the value of t_basic_site.site_type
     *
     * @mbggenerated
     */
    public String getSiteType() {
        return siteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_site.parent_site_code
     *
     * @return the value of t_basic_site.parent_site_code
     *
     * @mbggenerated
     */
    public String getParentSiteCode() {
        return parentSiteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_site.rd_status
     *
     * @return the value of t_basic_site.rd_status
     *
     * @mbggenerated
     */
    public Integer getRdStatus() {
        return rdStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_site.last_time
     *
     * @return the value of t_basic_site.last_time
     *
     * @mbggenerated
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_site.creator
     *
     * @return the value of t_basic_site.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_site.create_time
     *
     * @return the value of t_basic_site.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_site.updator
     *
     * @return the value of t_basic_site.updator
     *
     * @mbggenerated
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_site.update_time
     *
     * @return the value of t_basic_site.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_basic_site.is_deleted
     *
     * @return the value of t_basic_site.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    @Override
    public String toString() {
        return "BasicSiteVO{" +
                "siteId=" + siteId +
                ", siteCode='" + siteCode + '\'' +
                ", siteName='" + siteName + '\'' +
                ", sitePinyin='" + sitePinyin + '\'' +
                ", siteType='" + siteType + '\'' +
                ", parentSiteCode='" + parentSiteCode + '\'' +
                ", rdStatus=" + rdStatus +
                ", lastTime=" + lastTime +
                ", creator='" + creator + '\'' +
                ", createTime=" + createTime +
                ", updator='" + updator + '\'' +
                ", updateTime=" + updateTime +
                ", isDeleted=" + isDeleted +
                '}';
    }
}