package com.quentin.example.domain;

import lombok.Data;

import java.util.Date;

@Data
public class BasicSiteVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.site_id
     *
     * @mbggenerated
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.site_code
     *
     * @mbggenerated
     */
    private String siteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.site_name
     *
     * @mbggenerated
     */
    private String siteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.site_pinyin
     *
     * @mbggenerated
     */
    private String sitePinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.site_type
     *
     * @mbggenerated
     */
    private String siteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.parent_site_code
     *
     * @mbggenerated
     */
    private String parentSiteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.rd_status
     *
     * @mbggenerated
     */
    private Integer rdStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.last_time
     *
     * @mbggenerated
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.updator
     *
     * @mbggenerated
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_basic_site.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    @Override
    public String toString() {
        return "BasicSiteVO{" +
                "siteId=" + siteId +
                ", siteCode='" + siteCode + '\'' +
                ", siteName='" + siteName + '\'' +
                ", sitePinyin='" + sitePinyin + '\'' +
                ", siteType='" + siteType + '\'' +
                ", parentSiteCode='" + parentSiteCode + '\'' +
                ", rdStatus=" + rdStatus +
                ", lastTime=" + lastTime +
                ", creator='" + creator + '\'' +
                ", createTime=" + createTime +
                ", updator='" + updator + '\'' +
                ", updateTime=" + updateTime +
                ", isDeleted=" + isDeleted +
                '}';
    }
}