package com.quentin.example.domain;

import java.math.BigDecimal;
import java.util.Date;

public class OptEwbVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.EWB_NO
     *
     * @mbggenerated
     */
    private String ewbNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.OPERATION_ID
     *
     * @mbggenerated
     */
    private Long operationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.EWB_DATE
     *
     * @mbggenerated
     */
    private Date ewbDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SEND_CUSTOMER_ID
     *
     * @mbggenerated
     */
    private Integer sendCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SEND_CUSTOMER_ADDRESS_ID
     *
     * @mbggenerated
     */
    private Integer sendCustomerAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.RECEIVE_CUSTOMER_ID
     *
     * @mbggenerated
     */
    private Integer receiveCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.RECEIVE_CUSTOMER_ADDRESS_ID
     *
     * @mbggenerated
     */
    private Integer receiveCustomerAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.PIECE
     *
     * @mbggenerated
     */
    private Integer piece;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.WEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CALC_WEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal calcWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.LENGTH
     *
     * @mbggenerated
     */
    private BigDecimal length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.WIDTH
     *
     * @mbggenerated
     */
    private BigDecimal width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.HIGH
     *
     * @mbggenerated
     */
    private BigDecimal high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.VOL
     *
     * @mbggenerated
     */
    private BigDecimal vol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.VOL_WEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal volWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.GOODS_TYPE_ID
     *
     * @mbggenerated
     */
    private Integer goodsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.GOODS_EXPLAIN
     *
     * @mbggenerated
     */
    private String goodsExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.PAY_SIDE_ID
     *
     * @mbggenerated
     */
    private Integer paySideId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.PAY_MODE_ID
     *
     * @mbggenerated
     */
    private Integer payModeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CLASS_ID
     *
     * @mbggenerated
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.PICK_GOODS_MODE_ID
     *
     * @mbggenerated
     */
    private Integer pickGoodsModeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SMS_MODE_ID
     *
     * @mbggenerated
     */
    private Integer smsModeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.FREIGHT_CURRENCY_ID
     *
     * @mbggenerated
     */
    private Integer freightCurrencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.INSURED_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal insuredAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.INSURED_CURRENCY_ID
     *
     * @mbggenerated
     */
    private Integer insuredCurrencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal codCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_CURRENCY_ID
     *
     * @mbggenerated
     */
    private Integer codCurrencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_PAY_MODE_ID
     *
     * @mbggenerated
     */
    private Integer codPayModeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.REWB_NO
     *
     * @mbggenerated
     */
    private String rewbNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.INPUT_SITE_ID
     *
     * @mbggenerated
     */
    private Integer inputSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SEND_SITE_ID
     *
     * @mbggenerated
     */
    private Integer sendSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SALE_EMPLOYEE_ID
     *
     * @mbggenerated
     */
    private Integer saleEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.RECEIVE_EMPLOYEE_ID
     *
     * @mbggenerated
     */
    private Integer receiveEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.DISPATCH_SITE_ID
     *
     * @mbggenerated
     */
    private Integer dispatchSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.DISPATCH_EMPLOYEE_ID
     *
     * @mbggenerated
     */
    private Integer dispatchEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.EC_ID
     *
     * @mbggenerated
     */
    private Integer ecId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.EC_WAREHOUSE_ID
     *
     * @mbggenerated
     */
    private Integer ecWarehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.ORDER_NO
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.BL_SIGN
     *
     * @mbggenerated
     */
    private Short blSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.REFUND_FLAG
     *
     * @mbggenerated
     */
    private Short refundFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.WITHDRAW_FLAG
     *
     * @mbggenerated
     */
    private Short withdrawFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_FLAG_3
     *
     * @mbggenerated
     */
    private Short codFlag3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_FLAG_4
     *
     * @mbggenerated
     */
    private Short codFlag4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_FLAG_5
     *
     * @mbggenerated
     */
    private Short codFlag5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COD_FLAG_6
     *
     * @mbggenerated
     */
    private Short codFlag6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.REMARK_CLOB_ID
     *
     * @mbggenerated
     */
    private Integer remarkClobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CREATED_BY
     *
     * @mbggenerated
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CREATED_TIME
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MODIFIED_BY
     *
     * @mbggenerated
     */
    private Integer modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MODIFIED_TIME
     *
     * @mbggenerated
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.RD_STATUS
     *
     * @mbggenerated
     */
    private Short rdStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.FIRST_FREIGHT_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal firstFreightCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CHECK_STATUS
     *
     * @mbggenerated
     */
    private Short checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.PICKUP_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal pickupCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.FUEL_ADD_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal fuelAddCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.EC_IN_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal ecInCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.KFSLF_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal kfslfCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.KFBXF_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal kfbxfCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COUPON
     *
     * @mbggenerated
     */
    private String coupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.COUPON_RET_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal couponRetCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SERVICE_DIP_FLAG
     *
     * @mbggenerated
     */
    private Short serviceDipFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SERVICE_FIX_FLAG
     *
     * @mbggenerated
     */
    private Short serviceFixFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.REWARD_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal rewardCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.DELIVERY_DEMAND
     *
     * @mbggenerated
     */
    private String deliveryDemand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.DATA_SOURCE
     *
     * @mbggenerated
     */
    private Short dataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MAIN_HEWB_NO
     *
     * @mbggenerated
     */
    private String mainHewbNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MAIN_HEWB_NO_1
     *
     * @mbggenerated
     */
    private String mainHewbNo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SHIPPING_METHOD
     *
     * @mbggenerated
     */
    private Integer shippingMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.GOODS_CATEGORY
     *
     * @mbggenerated
     */
    private Short goodsCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CAN_GIVE_OUT
     *
     * @mbggenerated
     */
    private String canGiveOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.ISJZ
     *
     * @mbggenerated
     */
    private String isjz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.RETURN_FLAG
     *
     * @mbggenerated
     */
    private Short returnFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.OLD_EWB_NO
     *
     * @mbggenerated
     */
    private String oldEwbNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.IMG_DATE
     *
     * @mbggenerated
     */
    private Date imgDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.RETURN_DATE
     *
     * @mbggenerated
     */
    private Date returnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CAN_GIVE_OUTS
     *
     * @mbggenerated
     */
    private String canGiveOuts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MATCH_TYPE
     *
     * @mbggenerated
     */
    private Short matchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CUSTR_QUOTE_FEE
     *
     * @mbggenerated
     */
    private BigDecimal custrQuoteFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.FREIGHT_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal freightCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.FILL_STOREHOUSE
     *
     * @mbggenerated
     */
    private Short fillStorehouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MAPPING_VERSION
     *
     * @mbggenerated
     */
    private Long mappingVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.MAX_EDGE_LENGTH
     *
     * @mbggenerated
     */
    private BigDecimal maxEdgeLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.STAIRS_TYPE_ID
     *
     * @mbggenerated
     */
    private Integer stairsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.CARGO_TYPE_ID
     *
     * @mbggenerated
     */
    private Integer cargoTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.SPECIAL_PIECE
     *
     * @mbggenerated
     */
    private Integer specialPiece;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_OPT_EWB.UPSTAIRS_NEW_CHARGE
     *
     * @mbggenerated
     */
    private BigDecimal upstairsNewCharge;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HS_OPT_EWB
     *
     * @mbggenerated
     */
    public OptEwbVO(String ewbNo, Long operationId, Date ewbDate, Integer sendCustomerId, Integer sendCustomerAddressId, Integer receiveCustomerId, Integer receiveCustomerAddressId, Integer piece, BigDecimal weight, BigDecimal calcWeight, BigDecimal length, BigDecimal width, BigDecimal high, BigDecimal vol, BigDecimal volWeight, Integer goodsTypeId, String goodsExplain, Integer paySideId, Integer payModeId, Integer classId, Integer pickGoodsModeId, Integer smsModeId, Integer freightCurrencyId, BigDecimal insuredAmount, Integer insuredCurrencyId, BigDecimal codCharge, Integer codCurrencyId, Integer codPayModeId, String rewbNo, Integer inputSiteId, Integer sendSiteId, Integer saleEmployeeId, Integer receiveEmployeeId, Integer dispatchSiteId, Integer dispatchEmployeeId, Integer ecId, Integer ecWarehouseId, String orderNo, Short blSign, Short refundFlag, Short withdrawFlag, Short codFlag3, Short codFlag4, Short codFlag5, Short codFlag6, String remark, Integer remarkClobId, Integer createdBy, Date createdTime, Integer modifiedBy, Date modifiedTime, Short rdStatus, BigDecimal firstFreightCharge, Short checkStatus, BigDecimal pickupCharge, BigDecimal fuelAddCharge, BigDecimal ecInCharge, BigDecimal kfslfCharge, BigDecimal kfbxfCharge, String coupon, BigDecimal couponRetCharge, Short serviceDipFlag, Short serviceFixFlag, BigDecimal rewardCharge, String deliveryDemand, Short dataSource, String mainHewbNo, String mainHewbNo1, Integer shippingMethod, Short goodsCategory, String canGiveOut, String isjz, Short returnFlag, String oldEwbNo, Date imgDate, Date returnDate, String canGiveOuts, Short matchType, BigDecimal custrQuoteFee, BigDecimal freightCharge, Short fillStorehouse, Long mappingVersion, BigDecimal maxEdgeLength, Integer stairsTypeId, Integer cargoTypeId, Integer specialPiece, BigDecimal upstairsNewCharge) {
        this.ewbNo = ewbNo;
        this.operationId = operationId;
        this.ewbDate = ewbDate;
        this.sendCustomerId = sendCustomerId;
        this.sendCustomerAddressId = sendCustomerAddressId;
        this.receiveCustomerId = receiveCustomerId;
        this.receiveCustomerAddressId = receiveCustomerAddressId;
        this.piece = piece;
        this.weight = weight;
        this.calcWeight = calcWeight;
        this.length = length;
        this.width = width;
        this.high = high;
        this.vol = vol;
        this.volWeight = volWeight;
        this.goodsTypeId = goodsTypeId;
        this.goodsExplain = goodsExplain;
        this.paySideId = paySideId;
        this.payModeId = payModeId;
        this.classId = classId;
        this.pickGoodsModeId = pickGoodsModeId;
        this.smsModeId = smsModeId;
        this.freightCurrencyId = freightCurrencyId;
        this.insuredAmount = insuredAmount;
        this.insuredCurrencyId = insuredCurrencyId;
        this.codCharge = codCharge;
        this.codCurrencyId = codCurrencyId;
        this.codPayModeId = codPayModeId;
        this.rewbNo = rewbNo;
        this.inputSiteId = inputSiteId;
        this.sendSiteId = sendSiteId;
        this.saleEmployeeId = saleEmployeeId;
        this.receiveEmployeeId = receiveEmployeeId;
        this.dispatchSiteId = dispatchSiteId;
        this.dispatchEmployeeId = dispatchEmployeeId;
        this.ecId = ecId;
        this.ecWarehouseId = ecWarehouseId;
        this.orderNo = orderNo;
        this.blSign = blSign;
        this.refundFlag = refundFlag;
        this.withdrawFlag = withdrawFlag;
        this.codFlag3 = codFlag3;
        this.codFlag4 = codFlag4;
        this.codFlag5 = codFlag5;
        this.codFlag6 = codFlag6;
        this.remark = remark;
        this.remarkClobId = remarkClobId;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.modifiedBy = modifiedBy;
        this.modifiedTime = modifiedTime;
        this.rdStatus = rdStatus;
        this.firstFreightCharge = firstFreightCharge;
        this.checkStatus = checkStatus;
        this.pickupCharge = pickupCharge;
        this.fuelAddCharge = fuelAddCharge;
        this.ecInCharge = ecInCharge;
        this.kfslfCharge = kfslfCharge;
        this.kfbxfCharge = kfbxfCharge;
        this.coupon = coupon;
        this.couponRetCharge = couponRetCharge;
        this.serviceDipFlag = serviceDipFlag;
        this.serviceFixFlag = serviceFixFlag;
        this.rewardCharge = rewardCharge;
        this.deliveryDemand = deliveryDemand;
        this.dataSource = dataSource;
        this.mainHewbNo = mainHewbNo;
        this.mainHewbNo1 = mainHewbNo1;
        this.shippingMethod = shippingMethod;
        this.goodsCategory = goodsCategory;
        this.canGiveOut = canGiveOut;
        this.isjz = isjz;
        this.returnFlag = returnFlag;
        this.oldEwbNo = oldEwbNo;
        this.imgDate = imgDate;
        this.returnDate = returnDate;
        this.canGiveOuts = canGiveOuts;
        this.matchType = matchType;
        this.custrQuoteFee = custrQuoteFee;
        this.freightCharge = freightCharge;
        this.fillStorehouse = fillStorehouse;
        this.mappingVersion = mappingVersion;
        this.maxEdgeLength = maxEdgeLength;
        this.stairsTypeId = stairsTypeId;
        this.cargoTypeId = cargoTypeId;
        this.specialPiece = specialPiece;
        this.upstairsNewCharge = upstairsNewCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.EWB_NO
     *
     * @return the value of HS_OPT_EWB.EWB_NO
     *
     * @mbggenerated
     */
    public String getEwbNo() {
        return ewbNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.OPERATION_ID
     *
     * @return the value of HS_OPT_EWB.OPERATION_ID
     *
     * @mbggenerated
     */
    public Long getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.EWB_DATE
     *
     * @return the value of HS_OPT_EWB.EWB_DATE
     *
     * @mbggenerated
     */
    public Date getEwbDate() {
        return ewbDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.SEND_CUSTOMER_ID
     *
     * @return the value of HS_OPT_EWB.SEND_CUSTOMER_ID
     *
     * @mbggenerated
     */
    public Integer getSendCustomerId() {
        return sendCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.SEND_CUSTOMER_ADDRESS_ID
     *
     * @return the value of HS_OPT_EWB.SEND_CUSTOMER_ADDRESS_ID
     *
     * @mbggenerated
     */
    public Integer getSendCustomerAddressId() {
        return sendCustomerAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.RECEIVE_CUSTOMER_ID
     *
     * @return the value of HS_OPT_EWB.RECEIVE_CUSTOMER_ID
     *
     * @mbggenerated
     */
    public Integer getReceiveCustomerId() {
        return receiveCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.RECEIVE_CUSTOMER_ADDRESS_ID
     *
     * @return the value of HS_OPT_EWB.RECEIVE_CUSTOMER_ADDRESS_ID
     *
     * @mbggenerated
     */
    public Integer getReceiveCustomerAddressId() {
        return receiveCustomerAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.PIECE
     *
     * @return the value of HS_OPT_EWB.PIECE
     *
     * @mbggenerated
     */
    public Integer getPiece() {
        return piece;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.WEIGHT
     *
     * @return the value of HS_OPT_EWB.WEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.CALC_WEIGHT
     *
     * @return the value of HS_OPT_EWB.CALC_WEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getCalcWeight() {
        return calcWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.LENGTH
     *
     * @return the value of HS_OPT_EWB.LENGTH
     *
     * @mbggenerated
     */
    public BigDecimal getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.WIDTH
     *
     * @return the value of HS_OPT_EWB.WIDTH
     *
     * @mbggenerated
     */
    public BigDecimal getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.HIGH
     *
     * @return the value of HS_OPT_EWB.HIGH
     *
     * @mbggenerated
     */
    public BigDecimal getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.VOL
     *
     * @return the value of HS_OPT_EWB.VOL
     *
     * @mbggenerated
     */
    public BigDecimal getVol() {
        return vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.VOL_WEIGHT
     *
     * @return the value of HS_OPT_EWB.VOL_WEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getVolWeight() {
        return volWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.GOODS_TYPE_ID
     *
     * @return the value of HS_OPT_EWB.GOODS_TYPE_ID
     *
     * @mbggenerated
     */
    public Integer getGoodsTypeId() {
        return goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.GOODS_EXPLAIN
     *
     * @return the value of HS_OPT_EWB.GOODS_EXPLAIN
     *
     * @mbggenerated
     */
    public String getGoodsExplain() {
        return goodsExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.PAY_SIDE_ID
     *
     * @return the value of HS_OPT_EWB.PAY_SIDE_ID
     *
     * @mbggenerated
     */
    public Integer getPaySideId() {
        return paySideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.PAY_MODE_ID
     *
     * @return the value of HS_OPT_EWB.PAY_MODE_ID
     *
     * @mbggenerated
     */
    public Integer getPayModeId() {
        return payModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.CLASS_ID
     *
     * @return the value of HS_OPT_EWB.CLASS_ID
     *
     * @mbggenerated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.PICK_GOODS_MODE_ID
     *
     * @return the value of HS_OPT_EWB.PICK_GOODS_MODE_ID
     *
     * @mbggenerated
     */
    public Integer getPickGoodsModeId() {
        return pickGoodsModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.SMS_MODE_ID
     *
     * @return the value of HS_OPT_EWB.SMS_MODE_ID
     *
     * @mbggenerated
     */
    public Integer getSmsModeId() {
        return smsModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.FREIGHT_CURRENCY_ID
     *
     * @return the value of HS_OPT_EWB.FREIGHT_CURRENCY_ID
     *
     * @mbggenerated
     */
    public Integer getFreightCurrencyId() {
        return freightCurrencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.INSURED_AMOUNT
     *
     * @return the value of HS_OPT_EWB.INSURED_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getInsuredAmount() {
        return insuredAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.INSURED_CURRENCY_ID
     *
     * @return the value of HS_OPT_EWB.INSURED_CURRENCY_ID
     *
     * @mbggenerated
     */
    public Integer getInsuredCurrencyId() {
        return insuredCurrencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.COD_CHARGE
     *
     * @return the value of HS_OPT_EWB.COD_CHARGE
     *
     * @mbggenerated
     */
    public BigDecimal getCodCharge() {
        return codCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.COD_CURRENCY_ID
     *
     * @return the value of HS_OPT_EWB.COD_CURRENCY_ID
     *
     * @mbggenerated
     */
    public Integer getCodCurrencyId() {
        return codCurrencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.COD_PAY_MODE_ID
     *
     * @return the value of HS_OPT_EWB.COD_PAY_MODE_ID
     *
     * @mbggenerated
     */
    public Integer getCodPayModeId() {
        return codPayModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.REWB_NO
     *
     * @return the value of HS_OPT_EWB.REWB_NO
     *
     * @mbggenerated
     */
    public String getRewbNo() {
        return rewbNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.INPUT_SITE_ID
     *
     * @return the value of HS_OPT_EWB.INPUT_SITE_ID
     *
     * @mbggenerated
     */
    public Integer getInputSiteId() {
        return inputSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.SEND_SITE_ID
     *
     * @return the value of HS_OPT_EWB.SEND_SITE_ID
     *
     * @mbggenerated
     */
    public Integer getSendSiteId() {
        return sendSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.SALE_EMPLOYEE_ID
     *
     * @return the value of HS_OPT_EWB.SALE_EMPLOYEE_ID
     *
     * @mbggenerated
     */
    public Integer getSaleEmployeeId() {
        return saleEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.RECEIVE_EMPLOYEE_ID
     *
     * @return the value of HS_OPT_EWB.RECEIVE_EMPLOYEE_ID
     *
     * @mbggenerated
     */
    public Integer getReceiveEmployeeId() {
        return receiveEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.DISPATCH_SITE_ID
     *
     * @return the value of HS_OPT_EWB.DISPATCH_SITE_ID
     *
     * @mbggenerated
     */
    public Integer getDispatchSiteId() {
        return dispatchSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.DISPATCH_EMPLOYEE_ID
     *
     * @return the value of HS_OPT_EWB.DISPATCH_EMPLOYEE_ID
     *
     * @mbggenerated
     */
    public Integer getDispatchEmployeeId() {
        return dispatchEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.EC_ID
     *
     * @return the value of HS_OPT_EWB.EC_ID
     *
     * @mbggenerated
     */
    public Integer getEcId() {
        return ecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.EC_WAREHOUSE_ID
     *
     * @return the value of HS_OPT_EWB.EC_WAREHOUSE_ID
     *
     * @mbggenerated
     */
    public Integer getEcWarehouseId() {
        return ecWarehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.ORDER_NO
     *
     * @return the value of HS_OPT_EWB.ORDER_NO
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.BL_SIGN
     *
     * @return the value of HS_OPT_EWB.BL_SIGN
     *
     * @mbggenerated
     */
    public Short getBlSign() {
        return blSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.REFUND_FLAG
     *
     * @return the value of HS_OPT_EWB.REFUND_FLAG
     *
     * @mbggenerated
     */
    public Short getRefundFlag() {
        return refundFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.WITHDRAW_FLAG
     *
     * @return the value of HS_OPT_EWB.WITHDRAW_FLAG
     *
     * @mbggenerated
     */
    public Short getWithdrawFlag() {
        return withdrawFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.COD_FLAG_3
     *
     * @return the value of HS_OPT_EWB.COD_FLAG_3
     *
     * @mbggenerated
     */
    public Short getCodFlag3() {
        return codFlag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.COD_FLAG_4
     *
     * @return the value of HS_OPT_EWB.COD_FLAG_4
     *
     * @mbggenerated
     */
    public Short getCodFlag4() {
        return codFlag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.COD_FLAG_5
     *
     * @return the value of HS_OPT_EWB.COD_FLAG_5
     *
     * @mbggenerated
     */
    public Short getCodFlag5() {
        return codFlag5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.COD_FLAG_6
     *
     * @return the value of HS_OPT_EWB.COD_FLAG_6
     *
     * @mbggenerated
     */
    public Short getCodFlag6() {
        return codFlag6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.REMARK
     *
     * @return the value of HS_OPT_EWB.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.REMARK_CLOB_ID
     *
     * @return the value of HS_OPT_EWB.REMARK_CLOB_ID
     *
     * @mbggenerated
     */
    public Integer getRemarkClobId() {
        return remarkClobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.CREATED_BY
     *
     * @return the value of HS_OPT_EWB.CREATED_BY
     *
     * @mbggenerated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.CREATED_TIME
     *
     * @return the value of HS_OPT_EWB.CREATED_TIME
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.MODIFIED_BY
     *
     * @return the value of HS_OPT_EWB.MODIFIED_BY
     *
     * @mbggenerated
     */
    public Integer getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.MODIFIED_TIME
     *
     * @return the value of HS_OPT_EWB.MODIFIED_TIME
     *
     * @mbggenerated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.RD_STATUS
     *
     * @return the value of HS_OPT_EWB.RD_STATUS
     *
     * @mbggenerated
     */
    public Short getRdStatus() {
        return rdStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.FIRST_FREIGHT_CHARGE
     *
     * @return the value of HS_OPT_EWB.FIRST_FREIGHT_CHARGE
     *
     * @mbggenerated
     */
    public BigDecimal getFirstFreightCharge() {
        return firstFreightCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.CHECK_STATUS
     *
     * @return the value of HS_OPT_EWB.CHECK_STATUS
     *
     * @mbggenerated
     */
    public Short getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.PICKUP_CHARGE
     *
     * @return the value of HS_OPT_EWB.PICKUP_CHARGE
     *
     * @mbggenerated
     */
    public BigDecimal getPickupCharge() {
        return pickupCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.FUEL_ADD_CHARGE
     *
     * @return the value of HS_OPT_EWB.FUEL_ADD_CHARGE
     *
     * @mbggenerated
     */
    public BigDecimal getFuelAddCharge() {
        return fuelAddCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.EC_IN_CHARGE
     *
     * @return the value of HS_OPT_EWB.EC_IN_CHARGE
     *
     * @mbggenerated
     */
    public BigDecimal getEcInCharge() {
        return ecInCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.KFSLF_CHARGE
     *
     * @return the value of HS_OPT_EWB.KFSLF_CHARGE
     *
     * @mbggenerated
     */
    public BigDecimal getKfslfCharge() {
        return kfslfCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.KFBXF_CHARGE
     *
     * @return the value of HS_OPT_EWB.KFBXF_CHARGE
     *
     * @mbggenerated
     */
    public BigDecimal getKfbxfCharge() {
        return kfbxfCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.COUPON
     *
     * @return the value of HS_OPT_EWB.COUPON
     *
     * @mbggenerated
     */
    public String getCoupon() {
        return coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.COUPON_RET_CHARGE
     *
     * @return the value of HS_OPT_EWB.COUPON_RET_CHARGE
     *
     * @mbggenerated
     */
    public BigDecimal getCouponRetCharge() {
        return couponRetCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.SERVICE_DIP_FLAG
     *
     * @return the value of HS_OPT_EWB.SERVICE_DIP_FLAG
     *
     * @mbggenerated
     */
    public Short getServiceDipFlag() {
        return serviceDipFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.SERVICE_FIX_FLAG
     *
     * @return the value of HS_OPT_EWB.SERVICE_FIX_FLAG
     *
     * @mbggenerated
     */
    public Short getServiceFixFlag() {
        return serviceFixFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.REWARD_CHARGE
     *
     * @return the value of HS_OPT_EWB.REWARD_CHARGE
     *
     * @mbggenerated
     */
    public BigDecimal getRewardCharge() {
        return rewardCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.DELIVERY_DEMAND
     *
     * @return the value of HS_OPT_EWB.DELIVERY_DEMAND
     *
     * @mbggenerated
     */
    public String getDeliveryDemand() {
        return deliveryDemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.DATA_SOURCE
     *
     * @return the value of HS_OPT_EWB.DATA_SOURCE
     *
     * @mbggenerated
     */
    public Short getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.MAIN_HEWB_NO
     *
     * @return the value of HS_OPT_EWB.MAIN_HEWB_NO
     *
     * @mbggenerated
     */
    public String getMainHewbNo() {
        return mainHewbNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.MAIN_HEWB_NO_1
     *
     * @return the value of HS_OPT_EWB.MAIN_HEWB_NO_1
     *
     * @mbggenerated
     */
    public String getMainHewbNo1() {
        return mainHewbNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.SHIPPING_METHOD
     *
     * @return the value of HS_OPT_EWB.SHIPPING_METHOD
     *
     * @mbggenerated
     */
    public Integer getShippingMethod() {
        return shippingMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.GOODS_CATEGORY
     *
     * @return the value of HS_OPT_EWB.GOODS_CATEGORY
     *
     * @mbggenerated
     */
    public Short getGoodsCategory() {
        return goodsCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.CAN_GIVE_OUT
     *
     * @return the value of HS_OPT_EWB.CAN_GIVE_OUT
     *
     * @mbggenerated
     */
    public String getCanGiveOut() {
        return canGiveOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.ISJZ
     *
     * @return the value of HS_OPT_EWB.ISJZ
     *
     * @mbggenerated
     */
    public String getIsjz() {
        return isjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.RETURN_FLAG
     *
     * @return the value of HS_OPT_EWB.RETURN_FLAG
     *
     * @mbggenerated
     */
    public Short getReturnFlag() {
        return returnFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.OLD_EWB_NO
     *
     * @return the value of HS_OPT_EWB.OLD_EWB_NO
     *
     * @mbggenerated
     */
    public String getOldEwbNo() {
        return oldEwbNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.IMG_DATE
     *
     * @return the value of HS_OPT_EWB.IMG_DATE
     *
     * @mbggenerated
     */
    public Date getImgDate() {
        return imgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.RETURN_DATE
     *
     * @return the value of HS_OPT_EWB.RETURN_DATE
     *
     * @mbggenerated
     */
    public Date getReturnDate() {
        return returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.CAN_GIVE_OUTS
     *
     * @return the value of HS_OPT_EWB.CAN_GIVE_OUTS
     *
     * @mbggenerated
     */
    public String getCanGiveOuts() {
        return canGiveOuts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.MATCH_TYPE
     *
     * @return the value of HS_OPT_EWB.MATCH_TYPE
     *
     * @mbggenerated
     */
    public Short getMatchType() {
        return matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.CUSTR_QUOTE_FEE
     *
     * @return the value of HS_OPT_EWB.CUSTR_QUOTE_FEE
     *
     * @mbggenerated
     */
    public BigDecimal getCustrQuoteFee() {
        return custrQuoteFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.FREIGHT_CHARGE
     *
     * @return the value of HS_OPT_EWB.FREIGHT_CHARGE
     *
     * @mbggenerated
     */
    public BigDecimal getFreightCharge() {
        return freightCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.FILL_STOREHOUSE
     *
     * @return the value of HS_OPT_EWB.FILL_STOREHOUSE
     *
     * @mbggenerated
     */
    public Short getFillStorehouse() {
        return fillStorehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.MAPPING_VERSION
     *
     * @return the value of HS_OPT_EWB.MAPPING_VERSION
     *
     * @mbggenerated
     */
    public Long getMappingVersion() {
        return mappingVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.MAX_EDGE_LENGTH
     *
     * @return the value of HS_OPT_EWB.MAX_EDGE_LENGTH
     *
     * @mbggenerated
     */
    public BigDecimal getMaxEdgeLength() {
        return maxEdgeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.STAIRS_TYPE_ID
     *
     * @return the value of HS_OPT_EWB.STAIRS_TYPE_ID
     *
     * @mbggenerated
     */
    public Integer getStairsTypeId() {
        return stairsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.CARGO_TYPE_ID
     *
     * @return the value of HS_OPT_EWB.CARGO_TYPE_ID
     *
     * @mbggenerated
     */
    public Integer getCargoTypeId() {
        return cargoTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.SPECIAL_PIECE
     *
     * @return the value of HS_OPT_EWB.SPECIAL_PIECE
     *
     * @mbggenerated
     */
    public Integer getSpecialPiece() {
        return specialPiece;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_OPT_EWB.UPSTAIRS_NEW_CHARGE
     *
     * @return the value of HS_OPT_EWB.UPSTAIRS_NEW_CHARGE
     *
     * @mbggenerated
     */
    public BigDecimal getUpstairsNewCharge() {
        return upstairsNewCharge;
    }

    @Override
    public String toString() {
        return "OptEwbVO{" +
                "ewbNo='" + ewbNo + '\'' +
                ", operationId=" + operationId +
                ", ewbDate=" + ewbDate +
                ", sendCustomerId=" + sendCustomerId +
                ", sendCustomerAddressId=" + sendCustomerAddressId +
                ", receiveCustomerId=" + receiveCustomerId +
                ", receiveCustomerAddressId=" + receiveCustomerAddressId +
                ", piece=" + piece +
                ", weight=" + weight +
                ", calcWeight=" + calcWeight +
                ", length=" + length +
                ", width=" + width +
                ", high=" + high +
                ", vol=" + vol +
                ", volWeight=" + volWeight +
                ", goodsTypeId=" + goodsTypeId +
                ", goodsExplain='" + goodsExplain + '\'' +
                ", paySideId=" + paySideId +
                ", payModeId=" + payModeId +
                ", classId=" + classId +
                ", pickGoodsModeId=" + pickGoodsModeId +
                ", smsModeId=" + smsModeId +
                ", freightCurrencyId=" + freightCurrencyId +
                ", insuredAmount=" + insuredAmount +
                ", insuredCurrencyId=" + insuredCurrencyId +
                ", codCharge=" + codCharge +
                ", codCurrencyId=" + codCurrencyId +
                ", codPayModeId=" + codPayModeId +
                ", rewbNo='" + rewbNo + '\'' +
                ", inputSiteId=" + inputSiteId +
                ", sendSiteId=" + sendSiteId +
                ", saleEmployeeId=" + saleEmployeeId +
                ", receiveEmployeeId=" + receiveEmployeeId +
                ", dispatchSiteId=" + dispatchSiteId +
                ", dispatchEmployeeId=" + dispatchEmployeeId +
                ", ecId=" + ecId +
                ", ecWarehouseId=" + ecWarehouseId +
                ", orderNo='" + orderNo + '\'' +
                ", blSign=" + blSign +
                ", refundFlag=" + refundFlag +
                ", withdrawFlag=" + withdrawFlag +
                ", codFlag3=" + codFlag3 +
                ", codFlag4=" + codFlag4 +
                ", codFlag5=" + codFlag5 +
                ", codFlag6=" + codFlag6 +
                ", remark='" + remark + '\'' +
                ", remarkClobId=" + remarkClobId +
                ", createdBy=" + createdBy +
                ", createdTime=" + createdTime +
                ", modifiedBy=" + modifiedBy +
                ", modifiedTime=" + modifiedTime +
                ", rdStatus=" + rdStatus +
                ", firstFreightCharge=" + firstFreightCharge +
                ", checkStatus=" + checkStatus +
                ", pickupCharge=" + pickupCharge +
                ", fuelAddCharge=" + fuelAddCharge +
                ", ecInCharge=" + ecInCharge +
                ", kfslfCharge=" + kfslfCharge +
                ", kfbxfCharge=" + kfbxfCharge +
                ", coupon='" + coupon + '\'' +
                ", couponRetCharge=" + couponRetCharge +
                ", serviceDipFlag=" + serviceDipFlag +
                ", serviceFixFlag=" + serviceFixFlag +
                ", rewardCharge=" + rewardCharge +
                ", deliveryDemand='" + deliveryDemand + '\'' +
                ", dataSource=" + dataSource +
                ", mainHewbNo='" + mainHewbNo + '\'' +
                ", mainHewbNo1='" + mainHewbNo1 + '\'' +
                ", shippingMethod=" + shippingMethod +
                ", goodsCategory=" + goodsCategory +
                ", canGiveOut='" + canGiveOut + '\'' +
                ", isjz='" + isjz + '\'' +
                ", returnFlag=" + returnFlag +
                ", oldEwbNo='" + oldEwbNo + '\'' +
                ", imgDate=" + imgDate +
                ", returnDate=" + returnDate +
                ", canGiveOuts='" + canGiveOuts + '\'' +
                ", matchType=" + matchType +
                ", custrQuoteFee=" + custrQuoteFee +
                ", freightCharge=" + freightCharge +
                ", fillStorehouse=" + fillStorehouse +
                ", mappingVersion=" + mappingVersion +
                ", maxEdgeLength=" + maxEdgeLength +
                ", stairsTypeId=" + stairsTypeId +
                ", cargoTypeId=" + cargoTypeId +
                ", specialPiece=" + specialPiece +
                ", upstairsNewCharge=" + upstairsNewCharge +
                '}';
    }
}