package com.quentin.example.domain;

import lombok.Data;

import java.util.Date;

@Data
public class RoleVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_sign
     *
     * @mbggenerated
     */
    private String roleSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.user_id_create
     *
     * @mbggenerated
     */
    private Long userIdCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;


}