server:
    # context-path: /myboot
    session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
    port: 8088
#    uri-encoding: utf-8
#    配置error信息是否包含堆栈信息(ON_TRACE_PARAM、NEVER（默认）、ALWAYS)
    error:
      include-stacktrace: ALWAYS

#系统定义随机数
myapp:
  # 随机字符串
  secret: ${random.value}
  # 随机int
  number: ${random.int}
  # 随机long
  bignumber: ${random.long}
  # 10以内的随机数
  numberlessthanten: ${random.int(10)}
  # 1024-65536的随机数
  numberinrange: ${random.int[1024,65536]}

ws:
  url: http://192.168.1.127:8085/services/NE8Service?wsdl
  nameSpace: http://web.operation.ne.chengfeng.com/
  bindingName: NE8ServiceServiceSoapBinding
  method: callNE8LogicToString
  loginUser: aneAdmin
  loginPwd: ane654321
  ip: 192.168.1.8

#jedis-cluster配置
spring:
  redis:
    cluster:
      nodes: 180.76.246.243:7000,180.76.246.243:7001,180.76.246.243:7002,180.76.246.243:7003,180.76.246.243:7004,180.76.246.243:7005
      connectionTimeout: 15000
      soTimeout: 15000
      maxRedirections: 5
      pool:
        maxTotal: 500
        maxIdle: 50
        minIdle: 0
        maxWaitMillis: 15000
