
spring:
# 应用配置
  application:
    name: quentin
# 多环境配置文件激活属性
  profiles:
    active: dev
# 远程工具设置
  devtools:
    remote:
      secret: mysecret

# 数据库连接信息配置
  datasource:
    druid:
      stat-view-servlet:
        allow: 192.168.1.112,127.0.0.1 # IP白名单 (没有配置或者为空，则允许所有访问)
        deny: 192.168.16.111 # IP黑名单 (存在共同时，deny优先于allow)
        login-username: admin # 用户名
        login-password: ygq123456 # 密码
        reset-enable: false # 禁用HTML页面上的“Reset All”功能
      web-stat-filter:
        # URL监控拦截URL
        url-pattern: "/ewb/*"
        # 忽略资源
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      filter:
        stat:
          log-slow-sql: true # 慢SQL记录
          slow-sql-millis: 20
        wall:
          enabled: true
          config:
            delete-allow: false
            drop-table-allow: false
     # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      url: jdbc:mysql://180.76.101.59:3306/quentinshiro?characterEncoding=utf8
      username: root
      password: root123456
      driver-class-name: com.mysql.jdbc.Driver
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 初始化大小，最小，最大活跃数
      initialSize: 1
      minIdle: 1
      maxActive: 66
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小，如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false。
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    second:
      url: jdbc:mysql://180.76.101.59:3306/quentinshiro?characterEncoding=utf8
      username: root
      password: root123456
      driver-class-name: com.mysql.jdbc.Driver
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 初始化大小，最小，最大活跃数
      initialSize: 1
      minIdle: 1
      maxActive: 88
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小，如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false。
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20


# freemarker模板引擎配置
  freemarker:
    cache: false
    check-template-location: true
    content-type: text/html
    suffix: .html
    charset: utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    settings:
      template_update_delay: 0
    request-context-attribute: request



#mybatis配置
mybatis:
#  配置映射类所在包名
  type-aliases-package: com.quentin.example.domain
#  配置mapper所在路径，数组
  mapper-locations: mybatis/mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名规则
    use-generated-keys: true  # 使用jdbc的getGeneratedKeys 获取数据库自增主键
    use-column-label: true # 使用列名替换别名 默认为true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl # 调试打印SQL
#  config-location: classpath:mybatis/mybatis-config.xml

pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 params: count\=countSql





