package com.quentin.example.domain.mapper;

import com.quentin.example.domain.BasicSiteVO;
import org.apache.ibatis.annotations.Insert;

public interface BasicSiteVOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_site
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_basic_site (site_id, site_code, ",
        "site_name, site_pinyin, ",
        "site_type, parent_site_code, ",
        "rd_status, last_time, ",
        "creator, create_time, ",
        "updator, update_time, ",
        "is_deleted)",
        "values (#{siteId,jdbcType=INTEGER}, #{siteCode,jdbcType=VARCHAR}, ",
        "#{siteName,jdbcType=VARCHAR}, #{sitePinyin,jdbcType=VARCHAR}, ",
        "#{siteType,jdbcType=VARCHAR}, #{parentSiteCode,jdbcType=VARCHAR}, ",
        "#{rdStatus,jdbcType=INTEGER}, #{lastTime,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updator,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{isDeleted,jdbcType=INTEGER})"
    })
    int insert(BasicSiteVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_basic_site
     *
     * @mbggenerated
     */
    int insertSelective(BasicSiteVO record);

    BasicSiteVO selectByCode(String siteCode);

}