package com.quentin.example.domain.mapper;

import com.quentin.example.domain.UserVO;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface UserVOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from sys_user",
        "where user_id = #{userId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sys_user (user_id, username, ",
        "name, password, ",
        "dept_id, email, mobile, ",
        "status, user_id_create, ",
        "gmt_create, gmt_modified, ",
        "sex, birth, pic_id, ",
        "live_address, hobby, ",
        "province, city, ",
        "district)",
        "values (#{userId,jdbcType=BIGINT}, #{username,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{deptId,jdbcType=BIGINT}, #{email,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=TINYINT}, #{userIdCreate,jdbcType=BIGINT}, ",
        "#{gmtCreate,jdbcType=TIMESTAMP}, #{gmtModified,jdbcType=TIMESTAMP}, ",
        "#{sex,jdbcType=BIGINT}, #{birth,jdbcType=TIMESTAMP}, #{picId,jdbcType=BIGINT}, ",
        "#{liveAddress,jdbcType=VARCHAR}, #{hobby,jdbcType=VARCHAR}, ",
        "#{province,jdbcType=VARCHAR}, #{city,jdbcType=VARCHAR}, ",
        "#{district,jdbcType=VARCHAR})"
    })
    int insert(UserVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insertSelective(UserVO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserVO record);


    List<UserVO> queryByUserName(String userName);
}