package com.quentin.example.domain.mapper;

import com.quentin.example.config.dynamicsdb.DataSource;
import com.quentin.example.config.dynamicsdb.DataSourceEnum;
import com.quentin.example.domain.UserVO;
import org.apache.ibatis.annotations.*;

import java.util.List;

@DataSource(name = DataSourceEnum.predb)
public interface UserVOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insertSelective(UserVO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserVO record);


    List<UserVO> queryByUserName(@Param("userName") String userName);
}